name: Build and analyse

on:
  pull_request:
    paths:
      - .github/workflows/*
      - Configurations/*
      - MMTabBarView/**
      - Package.swift

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-14
            xcode: Xcode 15
            developer-dir: /Applications/Xcode_15.4.app/Contents/Developer
          - os: macos-15
            xcode: Xcode 16
            developer-dir: /Applications/Xcode_16.4.app/Contents/Developer
    name: Build with ${{ matrix.xcode }}
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: ${{ matrix.developer-dir }}
    timeout-minutes: 15

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Build and analyse framework with Xcode
      run: xcodebuild analyze -workspace default.xcworkspace -scheme MMTabBarView | xcpretty && exit ${PIPESTATUS[0]}
    - name: Build framework with Swift Package Manager
      run: swift build && exit ${PIPESTATUS[0]}
